---------------------------------------------------------
-- this tutorial is based off of teradata SQL syntax ----
---------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---- Building dat1 -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- this data table has information regarding patient characteristics

drop table INNOVATIONS_ANALYTICS.dat1;
create table INNOVATIONS_ANALYTICS.dat1(
	PAT_ID integer, 
	PAT_AGE integer, 
	PAT_GENDER varchar(100), 
	PAT_ETHNICITY varchar(100), 
	PAT_CLASS varchar(100));

/*
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(10, 58, 'FEMALE', 'INDIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(20, 49, 'MALE', 'BLACK', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(30, 68, 'MALE', 'ASIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(40, 57, 'FEMALE', 'BLACK', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(50, 64, 'FEMALE', 'WHITE', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(60, 54, 'FEMALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(70, 61, 'FEMALE', 'ASIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(80, 55, 'FEMALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(90, 46, 'MALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(100, 43, 'FEMALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(110, 31, 'FEMALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(120, 56, 'FEMALE', 'AUSTRALIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(130, 58, 'FEMALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(140, 50, 'FEMALE', 'ASIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(150, 67, 'MALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(160, 38, 'MALE', 'AUSTRALIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(170, 41, 'MALE', 'BLACK', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(180, 61, 'MALE', 'AUSTRALIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(190, 40, 'MALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(200, 67, 'FEMALE', 'AUSTRALIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(210, 51, 'MALE', 'WHITE', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(220, 39, 'FEMALE', 'ASIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(230, 44, 'MALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(240, 44, 'FEMALE', 'BLACK', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(250, 48, 'MALE', 'BLACK', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(260, 38, 'MALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(270, 25, 'MALE', 'ASIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(280, 37, 'MALE', 'AUSTRALIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(290, 36, 'MALE', 'AUSTRALIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(300, 54, 'FEMALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(310, 65, 'MALE', 'BLACK', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(320, 64, 'FEMALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(330, 50, 'MALE', 'AUSTRALIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(340, 45, 'FEMALE', 'AUSTRALIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(350, 55, 'MALE', 'ASIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(360, 52, 'MALE', 'BLACK', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(370, 58, 'FEMALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(380, 37, 'FEMALE', 'ASIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(390, 58, 'FEMALE', 'BLACK', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(400, 64, 'MALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(410, 58, 'FEMALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(420, 54, 'MALE', 'BLACK', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(430, 54, 'FEMALE', 'ASIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(440, 66, 'MALE', 'BLACK', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(450, 61, 'FEMALE', 'AUSTRALIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(460, 62, 'FEMALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(470, 36, 'FEMALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(480, 67, 'MALE', 'BLACK', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(490, 51, 'FEMALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(500, 24, 'MALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(510, 49, 'MALE', 'BLACK', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(520, 45, 'MALE', 'WHITE', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(530, 44, 'MALE', 'ASIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(540, 45, 'MALE', 'BLACK', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(550, 56, 'FEMALE', 'BLACK', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(560, 49, 'FEMALE', 'BLACK', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(570, 52, 'FEMALE', 'BLACK', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(580, 49, 'MALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(590, 48, 'MALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(600, 52, 'MALE', 'WHITE', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(610, 46, 'MALE', 'AUSTRALIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(620, 51, 'MALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(630, 61, 'MALE', 'ASIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(640, 51, 'MALE', 'BLACK', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(650, 64, 'MALE', 'AUSTRALIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(660, 41, 'FEMALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(670, 52, 'MALE', 'AUSTRALIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(680, 47, 'MALE', 'WHITE', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(690, 69, 'MALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(700, 53, 'MALE', 'AUSTRALIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(710, 46, 'FEMALE', 'BLACK', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(720, 53, 'FEMALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(730, 72, 'MALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(740, 44, 'MALE', 'AUSTRALIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(750, 61, 'MALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(760, 53, 'MALE', 'ASIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(770, 52, 'FEMALE', 'ASIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(780, 75, 'FEMALE', 'AUSTRALIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(790, 47, 'FEMALE', 'AUSTRALIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(800, 50, 'MALE', 'ASIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(810, 42, 'MALE', 'BLACK', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(820, 62, 'FEMALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(830, 63, 'MALE', 'BLACK', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(840, 54, 'FEMALE', 'ASIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(850, 54, 'FEMALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(860, 57, 'MALE', 'WHITE', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(870, 33, 'FEMALE', 'BLACK', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(880, 59, 'MALE', 'ASIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(890, 46, 'MALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(900, 65, 'FEMALE', 'INDIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(910, 45, 'FEMALE', 'ASIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(920, 46, 'MALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(930, 42, 'FEMALE', 'ASIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(940, 54, 'MALE', 'INDIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(950, 60, 'FEMALE', 'AUSTRALIAN', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(960, 54, 'FEMALE', 'AUSTRALIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(970, 53, 'FEMALE', 'BLACK', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(980, 65, 'MALE', 'WHITE', 'INPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(990, 47, 'FEMALE', 'INDIAN', 'OUTPATIENT');
insert into INNOVATIONS_ANALYTICS.dat1 (PAT_ID, PAT_AGE, PAT_GENDER, PAT_ETHNICITY, PAT_CLASS) values(1000, 56, 'MALE', 'INDIAN', 'INPATIENT');
*/

select 
	* 
from INNOVATIONS_ANALYTICS.dat1;

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---- Building dat2 -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- this data table has information regarding patient experience

drop table INNOVATIONS_ANALYTICS.dat2;
create table INNOVATIONS_ANALYTICS.dat2(
	PAT_ID integer, 
	DOCTOR varchar(100), 
	PAT_SCHEDULED timestamp(0), 
	PAT_ARRIVED timestamp(0), 
	PAT_DEPARTED timestamp(0), 
	PAT_WAITED_DAYS decimal(4,1), 
	PAT_LOS_HOURS decimal(4,1), 
	PRE_OPTIMIZATION varchar(100));

/*
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(10, 'NEWTON GARY', '2000-03-20 15:44:39', '2000-04-02 09:53:05', '2000-04-03 03:07:45', 12.7, 17.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(20, 'HEROOK DAVID', '2000-03-23 11:16:40', '2000-04-11 02:33:12', '2000-04-14 12:51:52', 18.6, 82.3, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(30, 'HIGGENS JOHN', '2000-03-24 11:46:26', '2000-04-15 23:15:15', '2000-04-20 06:29:17', 22.4, 103.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(40, 'HAMILTON JOSEPH', '2000-03-25 11:15:02', '2000-04-08 22:55:24', '2000-04-12 10:34:52', 14.4, 83.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(50, 'MURPHY ERIN', '2000-03-26 09:10:57', '2000-04-19 18:25:00', '2000-04-20 11:42:52', 24.3, 17.3, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(60, 'LONG DANIEL', '2000-03-27 12:58:06', '2000-04-19 03:08:08', '2000-04-22 02:27:56', 22.5, 71.3, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(70, 'HAMILTON JOSEPH', '2000-03-28 11:25:01', '2000-04-10 20:22:53', '2000-04-11 13:28:36', 13.3, 17.1, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(80, 'HAMILTON JOSEPH', '2000-03-30 10:44:07', '2000-04-17 14:00:38', '2000-04-22 21:53:50', 18.1, 127.9, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(90, 'LONG DANIEL', '2000-03-31 09:49:29', '2000-04-16 11:33:25', '2000-04-20 07:29:08', 16, 91.9, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(100, 'WEBBER NATHAN', '2000-04-01 08:52:42', '2000-04-13 01:27:52', '2000-04-15 20:09:48', 11.6, 66.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(110, 'WEBBER NATHAN', '2000-04-02 11:12:49', '2000-04-11 02:25:27', '2000-04-14 22:50:56', 8.6, 92.4, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(120, 'HIGGENS JOHN', '2000-04-03 13:28:17', '2000-04-18 11:35:49', '2000-04-23 01:45:14', 14.9, 110.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(130, 'MURPHY ERIN', '2000-04-04 12:58:06', '2000-04-22 13:51:44', '2000-04-25 17:03:00', 18, 75.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(140, 'LONG DANIEL', '2000-04-05 11:41:01', '2000-04-12 22:17:29', '2000-04-17 17:38:45', 7.4, 115.4, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(150, 'NEWTON GARY', '2000-04-07 13:02:57', '2000-04-26 02:33:01', '2000-04-28 15:17:25', 18.6, 60.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(160, 'WEBBER NATHAN', '2000-04-08 13:52:45', '2000-04-23 15:57:43', '2000-04-24 08:01:19', 15.1, 16.1, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(170, 'WEBBER NATHAN', '2000-04-09 09:55:15', '2000-04-25 20:54:09', '2000-04-28 10:15:33', 16.5, 61.4, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(180, 'NEWTON GARY', '2000-04-11 10:39:53', '2000-05-05 04:38:29', '2000-05-05 21:13:04', 23.7, 16.6, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(190, 'HEROOK DAVID', '2000-04-13 13:53:33', '2000-05-02 05:29:53', '2000-05-05 21:38:25', 18.7, 88.1, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(200, 'HEROOK DAVID', '2000-04-15 13:03:22', '2000-04-24 08:06:25', '2000-04-25 06:51:04', 8.8, 22.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(210, 'WEBBER NATHAN', '2000-04-16 12:59:54', '2000-04-28 07:43:30', '2000-04-29 01:27:54', 11.8, 17.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(220, 'NEWTON GARY', '2000-04-18 11:15:33', '2000-05-08 13:54:07', '2000-05-14 01:53:57', 20.1, 132, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(230, 'NEWTON GARY', '2000-04-19 10:48:23', '2000-05-08 17:18:42', '2000-05-11 23:30:03', 19.3, 78.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(240, 'LONG DANIEL', '2000-04-20 11:05:15', '2000-05-11 15:11:46', '2000-05-15 15:45:52', 21.2, 96.6, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(250, 'HEROOK DAVID', '2000-04-21 13:48:49', '2000-05-13 18:28:17', '2000-05-14 08:40:35', 22.2, 14.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(260, 'NEWTON GARY', '2000-04-22 09:54:52', '2000-05-13 12:15:22', '2000-05-16 11:58:09', 21.1, 71.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(270, 'NEWTON GARY', '2000-04-23 08:55:28', '2000-04-30 20:01:40', '2000-05-01 17:32:10', 7.5, 21.5, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(280, 'SMITH DARIN', '2000-04-24 13:57:41', '2000-05-11 09:36:42', '2000-05-15 03:45:15', 16.8, 90.1, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(290, 'HAMILTON JOSEPH', '2000-04-25 13:54:48', '2000-05-07 20:18:11', '2000-05-08 17:31:11', 12.3, 21.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(300, 'LONG DANIEL', '2000-04-26 12:29:26', '2000-05-10 02:15:16', '2000-05-14 03:27:01', 13.6, 97.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(310, 'SMITH DARIN', '2000-04-27 12:21:17', '2000-05-18 09:37:07', '2000-05-19 00:48:48', 20.9, 15.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(320, 'NEWTON GARY', '2000-04-28 08:52:49', '2000-05-07 07:23:16', '2000-05-12 07:38:08', 8.9, 120.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(330, 'HIGGENS JOHN', '2000-04-29 11:45:42', '2000-05-19 09:53:58', '2000-05-21 12:03:13', 19.9, 50.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(340, 'FINNIGAN JENNIFER', '2000-05-01 14:46:38', '2000-05-02 09:36:37', '2000-05-05 14:18:46', 0.8, 76.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(350, 'MURPHY ERIN', '2000-05-03 12:37:38', '2000-05-17 03:08:24', '2000-05-22 00:18:38', 13.6, 117.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(360, 'LONG DANIEL', '2000-05-04 10:28:28', '2000-05-19 04:28:34', '2000-05-19 19:07:03', 14.8, 14.6, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(370, 'NEWTON GARY', '2000-05-05 12:41:20', '2000-05-28 00:22:24', '2000-06-01 19:34:27', 22.5, 115.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(380, 'WEBBER NATHAN', '2000-05-06 12:53:21', '2000-05-13 01:56:57', '2000-05-16 21:16:45', 6.5, 91.3, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(390, 'ONEAL JAMES', '2000-05-07 11:43:54', '2000-05-27 05:04:12', '2000-05-31 14:01:20', 19.7, 105, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(400, 'ONEAL JAMES', '2000-05-09 12:46:10', '2000-05-23 01:14:32', '2000-05-26 07:36:07', 13.5, 78.4, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(410, 'HIGGENS JOHN', '2000-05-11 08:11:14', '2000-05-24 17:51:20', '2000-05-27 22:57:05', 13.4, 77.1, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(420, 'HIGGENS JOHN', '2000-05-12 09:19:42', '2000-05-31 07:48:05', '2000-06-04 12:41:43', 18.9, 100.9, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(430, 'HEROOK DAVID', '2000-05-13 10:36:20', '2000-05-30 08:49:53', '2000-05-30 18:40:49', 16.9, 9.8, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(440, 'WEBBER NATHAN', '2000-05-14 12:40:16', '2000-05-31 02:06:09', '2000-05-31 11:35:22', 16.6, 9.5, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(450, 'FINNIGAN JENNIFER', '2000-05-16 09:32:10', '2000-05-30 01:02:22', '2000-05-30 16:32:05', 13.6, 15.5, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(460, 'SMITH DARIN', '2000-05-17 08:16:46', '2000-06-06 13:33:32', '2000-06-09 14:48:41', 20.2, 73.3, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(470, 'HIGGENS JOHN', '2000-05-18 16:28:34', '2000-06-05 15:57:01', '2000-06-10 06:37:50', 18, 110.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(480, 'NEWTON GARY', '2000-05-20 12:15:44', '2000-05-29 16:32:45', '2000-06-02 07:49:08', 9.2, 87.3, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(490, 'FINNIGAN JENNIFER', '2000-05-22 15:09:27', '2000-06-05 06:52:49', '2000-06-09 03:48:44', 13.7, 92.9, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(500, 'SMITH DARIN', '2000-05-24 10:01:06', '2000-06-06 08:01:00', '2000-06-07 16:41:02', 12.9, 32.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(510, 'FINNIGAN JENNIFER', '2000-05-26 12:33:48', '2000-06-13 09:49:33', '2000-06-13 20:42:27', 17.9, 10.9, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(520, 'FINNIGAN JENNIFER', '2000-05-27 09:30:15', '2000-06-17 06:40:44', '2000-06-17 17:31:00', 20.9, 10.8, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(530, 'SMITH DARIN', '2000-05-30 15:46:56', '2000-06-17 20:52:28', '2000-06-20 14:47:21', 18.2, 65.9, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(540, 'LONG DANIEL', '2000-05-31 10:35:45', '2000-06-14 19:36:44', '2000-06-15 13:29:15', 14.4, 17.9, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(550, 'FINNIGAN JENNIFER', '2000-06-02 13:23:26', '2000-06-20 01:02:14', '2000-06-20 12:30:58', 17.5, 11.5, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(560, 'WEBBER NATHAN', '2000-06-04 08:01:56', '2000-06-21 07:57:46', '2000-06-21 20:27:12', 17, 12.5, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(570, 'SMITH DARIN', '2000-06-05 09:30:44', '2000-06-26 14:37:56', '2000-06-29 15:24:58', 21.2, 72.8, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(580, 'HEROOK DAVID', '2000-06-07 14:00:14', '2000-07-05 11:33:41', '2000-07-11 01:11:57', 27.9, 133.6, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(590, 'SMITH DARIN', '2000-06-08 09:05:19', '2000-06-17 20:32:48', '2000-06-23 08:21:21', 9.5, 131.8, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(600, 'HAMILTON JOSEPH', '2000-06-09 12:55:22', '2000-06-20 06:04:15', '2000-06-20 21:05:18', 10.7, 15, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(610, 'LONG DANIEL', '2000-06-10 11:36:42', '2000-06-23 03:22:36', '2000-06-23 23:53:51', 12.7, 20.5, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(620, 'HEROOK DAVID', '2000-06-11 09:33:01', '2000-06-29 17:42:24', '2000-07-03 16:58:55', 18.3, 95.3, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(630, 'MURPHY ERIN', '2000-06-13 16:06:21', '2000-07-06 15:46:11', '2000-07-10 18:11:56', 23, 98.4, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(640, 'LONG DANIEL', '2000-06-14 10:39:45', '2000-06-27 12:26:51', '2000-06-29 20:12:16', 13.1, 55.8, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(650, 'HAMILTON JOSEPH', '2000-06-15 14:47:26', '2000-07-05 07:38:55', '2000-07-05 22:20:26', 19.7, 14.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(660, 'HAMILTON JOSEPH', '2000-06-17 14:31:15', '2000-07-08 14:02:43', '2000-07-11 15:43:01', 21, 73.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(670, 'LONG DANIEL', '2000-06-18 10:27:22', '2000-07-02 21:21:01', '2000-07-06 01:03:31', 14.5, 75.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(680, 'HIGGENS JOHN', '2000-06-19 12:20:45', '2000-07-13 14:38:22', '2000-07-14 12:11:19', 24.1, 21.5, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(690, 'ONEAL JAMES', '2000-06-21 14:22:02', '2000-06-30 01:18:38', '2000-07-04 08:09:26', 8.5, 102.8, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(700, 'SMITH DARIN', '2000-06-22 14:57:54', '2000-07-05 08:48:54', '2000-07-10 03:01:58', 12.7, 114.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(710, 'NEWTON GARY', '2000-06-23 09:22:18', '2000-07-04 18:02:58', '2000-07-05 02:08:51', 11.4, 8.1, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(720, 'LONG DANIEL', '2000-06-25 08:26:10', '2000-07-10 15:25:39', '2000-07-16 13:34:31', 15.3, 142.1, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(730, 'MURPHY ERIN', '2000-06-29 10:27:12', '2000-07-19 02:53:42', '2000-07-21 16:10:10', 19.7, 61.3, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(740, 'HAMILTON JOSEPH', '2000-07-01 10:11:29', '2000-07-25 04:44:42', '2000-07-29 05:23:13', 23.8, 96.6, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(750, 'NEWTON GARY', '2000-07-03 08:05:40', '2000-07-17 11:33:27', '2000-07-22 08:17:49', 14.1, 116.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(760, 'HAMILTON JOSEPH', '2000-07-04 11:26:17', '2000-07-17 12:57:44', '2000-07-21 06:22:15', 13.1, 89.4, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(770, 'HAMILTON JOSEPH', '2000-07-05 13:37:57', '2000-07-22 12:37:27', '2000-07-28 16:15:39', 17, 147.6, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(780, 'WEBBER NATHAN', '2000-07-06 09:13:11', '2000-07-27 20:59:12', '2000-07-28 16:07:13', 21.5, 19.1, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(790, 'NEWTON GARY', '2000-07-08 13:04:42', '2000-07-17 07:43:35', '2000-07-21 00:19:35', 8.8, 88.6, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(800, 'FINNIGAN JENNIFER', '2000-07-09 12:38:33', '2000-07-22 19:46:15', '2000-07-26 08:09:27', 13.3, 84.4, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(810, 'WEBBER NATHAN', '2000-07-10 09:55:44', '2000-07-27 03:14:47', '2000-07-27 11:44:18', 16.7, 8.5, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(820, 'FINNIGAN JENNIFER', '2000-07-11 12:32:34', '2000-07-30 16:08:54', '2000-08-02 10:40:59', 19.2, 66.5, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(830, 'MURPHY ERIN', '2000-07-12 09:50:28', '2000-07-29 10:08:50', '2000-08-01 14:19:21', 17, 76.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(840, 'HEROOK DAVID', '2000-07-15 13:46:15', '2000-08-04 08:35:39', '2000-08-12 20:44:14', 19.8, 204.1, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(850, 'HEROOK DAVID', '2000-07-16 11:12:44', '2000-07-25 04:14:13', '2000-07-29 18:54:22', 8.7, 110.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(860, 'ONEAL JAMES', '2000-07-17 10:31:40', '2000-07-31 16:01:49', '2000-08-01 08:53:42', 14.2, 16.9, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(870, 'FINNIGAN JENNIFER', '2000-07-19 13:11:27', '2000-08-12 11:30:21', '2000-08-13 06:10:54', 23.9, 18.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(880, 'LONG DANIEL', '2000-07-20 13:18:50', '2000-08-03 11:46:21', '2000-08-05 15:24:19', 13.9, 51.6, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(890, 'MURPHY ERIN', '2000-07-22 12:53:27', '2000-08-08 06:05:14', '2000-08-11 07:13:52', 16.7, 73.1, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(900, 'ONEAL JAMES', '2000-07-23 10:23:30', '2000-08-11 20:56:51', '2000-08-15 19:51:53', 19.4, 94.9, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(910, 'HAMILTON JOSEPH', '2000-07-24 12:41:16', '2000-08-09 06:38:15', '2000-08-14 07:32:41', 15.7, 120.9, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(920, 'HAMILTON JOSEPH', '2000-07-26 12:04:05', '2000-08-11 13:08:57', '2000-08-15 20:46:04', 16, 103.6, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(930, 'HIGGENS JOHN', '2000-07-27 13:16:27', '2000-08-14 03:53:17', '2000-08-14 15:06:53', 17.6, 11.2, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(940, 'WEBBER NATHAN', '2000-07-28 12:37:27', '2000-08-12 22:35:43', '2000-08-13 12:44:20', 15.4, 14.1, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(950, 'WEBBER NATHAN', '2000-07-29 12:18:59', '2000-08-23 05:00:43', '2000-08-28 13:58:53', 24.7, 129, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(960, 'ONEAL JAMES', '2000-07-30 14:53:21', '2000-08-26 03:16:21', '2000-08-26 21:47:56', 26.5, 18.5, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(970, 'HEROOK DAVID', '2000-08-02 09:01:48', '2000-08-18 13:30:28', '2000-08-19 07:12:41', 16.2, 17.7, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(980, 'HIGGENS JOHN', '2000-08-03 12:35:57', '2000-08-12 05:16:19', '2000-08-15 22:13:46', 8.7, 89, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(990, 'HEROOK DAVID', '2000-08-04 13:10:45', '2000-08-16 05:21:40', '2000-08-16 18:51:44', 11.7, 13.5, 'Yes');
insert into INNOVATIONS_ANALYTICS.dat2 (PAT_ID, DOCTOR, PAT_SCHEDULED, PAT_ARRIVED, PAT_DEPARTED, PAT_WAITED_DAYS, PAT_LOS_HOURS, PRE_OPTIMIZATION) values(1000, 'ONEAL JAMES', '2000-08-05 11:45:52', '2000-08-23 02:48:40', '2000-08-26 19:17:45', 17.6, 88.5, 'Yes');
*/

select 
	* 
from INNOVATIONS_ANALYTICS.dat2;

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---- Building dat3 -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- this data table has information regarding whether a high risk patient ended up passing away in the hospital

drop table INNOVATIONS_ANALYTICS.dat3;
create table INNOVATIONS_ANALYTICS.dat3(
	PAT_ID integer, 
	PAT_MORTALITY integer);

/*
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(60, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(80, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(90, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(110, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(140, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(150, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(170, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(230, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(240, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(280, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(300, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(400, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(410, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(420, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(460, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(470, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(530, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(590, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(620, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(630, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(660, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(670, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(690, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(700, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(730, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(740, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(760, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(790, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(820, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(830, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(840, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(900, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(910, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(950, 1);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(980, 0);
insert into INNOVATIONS_ANALYTICS.dat3 (PAT_ID, PAT_MORTALITY) values(1000, 1);
*/

select 
	* 
from INNOVATIONS_ANALYTICS.dat3;

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---- Building dat4 -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- this data table has information regarding the unit transfers of patients that ended up passing away in the hospital

drop table INNOVATIONS_ANALYTICS.dat4;
create table INNOVATIONS_ANALYTICS.dat4(
	PAT_ID integer, 
	UNIT_ID varchar(100));

/*
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(90, 'A5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(90, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(90, 'D7');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(90, 'F3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(90, 'C2');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(140, 'D7');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(140, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(140, 'A5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(140, 'C2');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(140, 'F3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(150, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(150, 'A5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(150, 'D7');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(170, 'F3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(170, 'A5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(170, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(230, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(230, 'A5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(230, 'D7');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(230, 'C2');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(230, 'F3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(400, 'A5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(400, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(420, 'D7');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(420, 'F3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(420, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(420, 'A5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(420, 'C2');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(460, 'E5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(460, 'D7');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(630, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(630, 'A5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(630, 'F3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(660, 'D7');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(660, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(660, 'A5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(670, 'A5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(670, 'D7');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(670, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(670, 'F3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(840, 'D7');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(840, 'A5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(840, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(910, 'F3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(910, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(910, 'C2');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(910, 'A5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(910, 'D7');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(950, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(950, 'A5');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(950, 'D7');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(1000, 'B3');
insert into INNOVATIONS_ANALYTICS.dat4 (PAT_ID, UNIT_ID) values(1000, 'A5');
*/

select 
	* 
from INNOVATIONS_ANALYTICS.dat4;

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---- Manipulation ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- sampling ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

select 
	* 
from INNOVATIONS_ANALYTICS.dat1 
sample 10;

-- filtering -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- filter by columns ----------------------------------------------------------------------------------------------------------------------

select 
	PAT_GENDER, 
	PAT_ETHNICITY 
from INNOVATIONS_ANALYTICS.dat1 
sample 10;

-- filter by rows -------------------------------------------------------------------------------------------------------------------------

-- example 1
select 
	* 
from INNOVATIONS_ANALYTICS.dat1
where PAT_AGE >= 40
and PAT_CLASS = 'INPATIENT';

-- example 2
select 
	* 
from INNOVATIONS_ANALYTICS.dat1
where PAT_AGE between 40 and 60
and PAT_CLASS = 'INPATIENT';

-- example 3
select 
	* 
from INNOVATIONS_ANALYTICS.dat1
where PAT_AGE < 40 or PAT_AGE > 60
and PAT_CLASS = 'INPATIENT';

-- filter by rows and columns -------------------------------------------------------------------------------------------------------------

select 
	PAT_GENDER, 
	PAT_ETHNICITY 
from INNOVATIONS_ANALYTICS.dat1
where PAT_AGE > 40
and PAT_CLASS = 'INPATIENT';

-- filter unique values from a column -----------------------------------------------------------------------------------------------------

select distinct 
	PAT_ETHNICITY 
from INNOVATIONS_ANALYTICS.dat1;

-- filter unique values from multiple columns ---------------------------------------------------------------------------------------------

select distinct 
	PAT_GENDER, 
	PAT_ETHNICITY
from INNOVATIONS_ANALYTICS.dat1;

-- filter similar values ------------------------------------------------------------------------------------------------------------------

-- example 1: similar start
select 
	* 
from INNOVATIONS_ANALYTICS.dat1
where PAT_ETHNICITY like 'A%';

-- example 2: similar end
select 
	* 
from INNOVATIONS_ANALYTICS.dat1
where PAT_ETHNICITY like '%IAN';

-- example 3: similar middle
select 
	* 
from INNOVATIONS_ANALYTICS.dat2
where DOCTOR like '%ON%';

-- filter unsimilar values ----------------------------------------------------------------------------------------------------------------

select 
	* 
from INNOVATIONS_ANALYTICS.dat2
where DOCTOR not like '%ON%';

-- filter by a group of values ------------------------------------------------------------------------------------------------------------

select 
	* 
from INNOVATIONS_ANALYTICS.dat1
where PAT_ETHNICITY in('WHITE', 'BLACK');

-- ordering ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- order by decending ---------------------------------------------------------------------------------------------------------------------

select 
	* 
from INNOVATIONS_ANALYTICS.dat1 
order by PAT_AGE desc;

select 
	* 
from INNOVATIONS_ANALYTICS.dat1 
order by PAT_ETHNICITY desc;

-- order by acending ----------------------------------------------------------------------------------------------------------------------

select 
	* 
from INNOVATIONS_ANALYTICS.dat1 
order by PAT_AGE asc;

select 
	* 
from INNOVATIONS_ANALYTICS.dat1 
order by PAT_ETHNICITY asc;

-- filter & order -------------------------------------------------------------------------------------------------------------------------

select 
	* 
from INNOVATIONS_ANALYTICS.dat1
where PAT_ETHNICITY like '%IAN'
order by PAT_AGE asc;

-- data types ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- convert date time to date
select 
	cast(PAT_ARRIVED as date) 
from INNOVATIONS_ANALYTICS.dat2 
sample 10;

-- convert date time to time
select 
	cast(PAT_ARRIVED as time(0)) 
from INNOVATIONS_ANALYTICS.dat2 
sample 10;

-- extract year, month, day, hour, minute, and second from a timestamp
select
	PAT_ARRIVED,
	extract(year from PAT_ARRIVED) as "YEAR",
	extract(month from PAT_ARRIVED) as "MONTH",
	extract(day from PAT_ARRIVED) as "DAY",
	extract(hour from PAT_ARRIVED) as "HOUR",
	extract(minute from PAT_ARRIVED) as "MINUTE",
	extract(second from PAT_ARRIVED) as "SECOND"
from INNOVATIONS_ANALYTICS.dat2
order by 1 asc;

-- conversion and filtering
select 
	* 
from INNOVATIONS_ANALYTICS.dat2
where cast(PAT_SCHEDULED as date) >= '2000-05-27';

-- other data types -----------------------------------------------------------------------------------------------------------------------

-- strings
varchar(100)

-- numeric
decimal(10, 1)
integer

-- date time 
timestamp(0)

-- empty
NULL

-- case expressions ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

select 
	PAT_AGE,
	case
		when PAT_AGE >= 60 then 'OLD'
		when PAT_AGE >= 40 then 'MIDDLE AGED'
		else 'YOUNG'
	end
from INNOVATIONS_ANALYTICS.dat1
order by 1 asc;

-- set operations ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- union: rbind's unique values ----------------------------------------------------------------------------------------------------------

select 
	PAT_ID 
from INNOVATIONS_ANALYTICS.dat3
union
select 
	PAT_ID 
from INNOVATIONS_ANALYTICS.dat4;

-- union all: rbind ----------------------------------------------------------------------------------------------------------------------

select 
	PAT_ID 
from INNOVATIONS_ANALYTICS.dat3
union all
select 
	PAT_ID 
from INNOVATIONS_ANALYTICS.dat4;

-- intersect: returns duplicate rows -----------------------------------------------------------------------------------------------------

select 
	PAT_ID 
from INNOVATIONS_ANALYTICS.dat3
intersect
select 
	PAT_ID 
from INNOVATIONS_ANALYTICS.dat4;

-- except: returns unique rows -----------------------------------------------------------------------------------------------------------

select 
	PAT_ID 
from INNOVATIONS_ANALYTICS.dat3
except
select 
	PAT_ID 
from INNOVATIONS_ANALYTICS.dat4;

-- joining -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- inner joins: Returns all rows when there is at least one match in BOTH tables ---------------------------------------------------------

-- this table combines dat1 and dat2 into one full table
select 
	* 
from INNOVATIONS_ANALYTICS.dat1 as A
inner join INNOVATIONS_ANALYTICS.dat2 as B
on A.PAT_ID = B.PAT_ID;

-- this table combines the length of stay information in dat2 with the patient id and class information in dat1
select 
	A.PAT_ID, 
	A.PAT_CLASS, 
	B.PAT_LOS_HOURS 
from INNOVATIONS_ANALYTICS.dat1 as A
inner join INNOVATIONS_ANALYTICS.dat2 as B
on A.PAT_ID = B.PAT_ID;

-- left joins: Return all rows from the left table, and the matched rows from the right table --------------------------------------------

-- this table combines all the information in dat1 and dat2 that corresponds to the PAT_ID's available in dat3, into one full table
select 
	* 
from INNOVATIONS_ANALYTICS.dat3 as A
left join INNOVATIONS_ANALYTICS.dat1 as B
on A.PAT_ID = B.PAT_ID
left join INNOVATIONS_ANALYTICS.dat2 as C
on A.PAT_ID = C.PAT_ID;

-- this table combines length of stay in dat2 and class in dat1 with patient id and mortality in dat3
select 
	A.PAT_ID, 
	A.PAT_MORTALITY, 
	B.PAT_CLASS, 
	C.PAT_LOS_HOURS 
from INNOVATIONS_ANALYTICS.dat3 as A
left join INNOVATIONS_ANALYTICS.dat1 as B
on A.PAT_ID = B.PAT_ID
left join INNOVATIONS_ANALYTICS.dat2 as C
on A.PAT_ID = C.PAT_ID;

-- subqueries ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- this returns the patient characteristics from dat1 that spent more than 24 hours in the hospital as shown by dat2

select 
	* 
from INNOVATIONS_ANALYTICS.dat1 
where PAT_ID in
(
    select 
		PAT_ID 
	from INNOVATIONS_ANALYTICS.dat2 
	where PAT_LOS_HOURS > 24
);

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---- Arithmetic --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- computation ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- subtracting timestamps

alter table INNOVATIONS_ANALYTICS.dat2 
add LOS2 interval day to minute;

update INNOVATIONS_ANALYTICS.dat2 
set LOS2 = 
	(PAT_DEPARTED - PAT_ARRIVED) day to minute;

select * from INNOVATIONS_ANALYTICS.dat2;

alter table INNOVATIONS_ANALYTICS.dat2 
drop LOS2;

-- summary statistics
select
	count(*) as "count",
	min(PAT_LOS_HOURS) as "min",
	avg(PAT_LOS_HOURS) as mean,
	max(PAT_LOS_HOURS) as "max"
from INNOVATIONS_ANALYTICS.dat2;

-- computation and filtering -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

select
	count(*) as "newton_count",
	min(PAT_LOS_HOURS) as "newton_min",
	avg(PAT_LOS_HOURS) as "newton_mean",
	max(PAT_LOS_HOURS) as "newton_max"
from INNOVATIONS_ANALYTICS.dat2
where DOCTOR = 'NEWTON GARY';

-- computation and grouping --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

select
	DOCTOR,
	count(*) as "count",
	min(PAT_LOS_HOURS) as "min",
	avg(PAT_LOS_HOURS) as mean,
	max(PAT_LOS_HOURS) as "max"
from INNOVATIONS_ANALYTICS.dat2
group by 1;

-- computation and case expressions ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

select
	(sum(
		case
			when PAT_LOS_HOURS > 40 then 1.00
			else 0.00
		end
	) / count(*)) * 100 as "LOS > 40 hours (%)"
from INNOVATIONS_ANALYTICS.dat2;

-- computation and joins -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- this table counts the number of transfers a patient made as well as their ID, class, and LOS

select 
	A.PAT_ID, 
	count(A.UNIT_ID) - 1 as PAT_TRANSFERS, 
	B.PAT_CLASS, 
	C.PAT_LOS_HOURS 
from INNOVATIONS_ANALYTICS.dat4 as A
left join INNOVATIONS_ANALYTICS.dat1 as B
on A.PAT_ID = B.PAT_ID
left join INNOVATIONS_ANALYTICS.dat2 as C
on A.PAT_ID = C.PAT_ID
group by 1, 3, 4;

-- this table includes summary statistics on LOS by class

select 
	A.PAT_CLASS, 
	count(*) as "count",
	min(B.PAT_LOS_HOURS) as "min",
	avg(B.PAT_LOS_HOURS) as mean,
	max(B.PAT_LOS_HOURS) as "max" 
from INNOVATIONS_ANALYTICS.dat1 as A
inner join INNOVATIONS_ANALYTICS.dat2 as B
on A.PAT_ID = B.PAT_ID
group by 1;

-- computation and subqueries ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- this table includes summary statistics on LOS for inpatient

select
	count(*) as "inpatient_count",
	min(PAT_LOS_HOURS) as "inpatient_min",
	avg(PAT_LOS_HOURS) as "inpatient_mean",
	max(PAT_LOS_HOURS) as "inpatient_max"
from INNOVATIONS_ANALYTICS.dat2
where PAT_ID in
(
    select 
		PAT_ID 
	from INNOVATIONS_ANALYTICS.dat1 
	where PAT_CLASS = 'INPATIENT'
);




















